services:
  app:
    build:
      context: .
    container_name: my-php-container
    ports:
      - "8080:80" # Expose le serveur PHP sur le port 8080
    volumes:
      - ./:/var/www/html # Monte le répertoire local dans le conteneur
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.11 # Utilise l'image MariaDB pour correspondre à AlwaysData
    container_name: my-db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Mot de passe root pour MariaDB
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Nom de la base de données par défaut
      MYSQL_USER: ${MYSQL_USER} # Utilisateur MariaDB
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Mot de passe utilisateur
    ports:
      - "3306:3306" # Expose la base de données sur le port 3306
    volumes:
      - db_data:/var/lib/mysql # Garde les données persistantes localement
    networks:
      - app-network

networks:
  app-network: # Crée un réseau partagé pour les services
    driver: bridge

volumes:
  db_data: # Volume pour les données MariaDB persistantes
