version: "3.8"

services:
  app:
    build:
      context: .
    container_name: lesptitplats-php-lesPtitsPlats
    ports:
      - "8000:80"  # Accéder à l'application via localhost:8000
    env_file:
      - .env       # Charger les variables d'environnement
    depends_on:
      - db
      - mongo
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mariadb:10.11
    container_name: lesptitplats-db-lesPtitsPlats
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: lesptitplats-mongo-lesPtitsPlats
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  mongo_data:
